### ISSUE TITLE
Check failed: allow_missing: Device API gpu is not enabled. Please install the cuda version of dgl.

### ISSUE THREAD

**Issue by UtkrishtP** [initzhang/dc_dgl#1]
## ❓ Questions and Help

Hello Team,
Im trying to install a CUDA build of DGL from source of a this repo
I followed the install docs using conda env and the following commands :

```
cmake -DUSE_CUDA=ON -DBUILD_TORCH=ON ..
```

The DGL version shown here is:
```
$ pip list | grep dgl
dgl                      0.9
```

The error thrown is :
```
Traceback (most recent call last):
  File "/storage/utk/DUCATI_SIGMOD/run_allocate.py", line 60, in <module>
    graph, n_classes = load_dc_realtime_process(args)
  File "/storage/utk/DUCATI_SIGMOD/load_graph.py", line 86, in load_dc_realtime_process
    graph.pin_memory_()
  File "/storage/utk/miniconda3/envs/ducati/lib/python3.10/site-packages/dgl-0.9-py3.10-linux-x86_64.egg/dgl/heterograph.py", line 5552, in pin_memory_
    self._graph.pin_memory_()
  File "/storage/utk/miniconda3/envs/ducati/lib/python3.10/site-packages/dgl-0.9-py3.10-linux-x86_64.egg/dgl/heterograph_index.py", line 250, in pin_memory_
    return _CAPI_DGLHeteroPinMemory_(self)
  File "/storage/utk/miniconda3/envs/ducati/lib/python3.10/site-packages/dgl-0.9-py3.10-linux-x86_64.egg/dgl/_ffi/_ctypes/function.py", line 188, in __call__
    check_call(_LIB.DGLFuncCall(
  File "/storage/utk/miniconda3/envs/ducati/lib/python3.10/site-packages/dgl-0.9-py3.10-linux-x86_64.egg/dgl/_ffi/base.py", line 65, in check_call
    raise DGLError(py_str(_LIB.DGLGetLastError()))
dgl._ffi.base.DGLError: [16:21:20] /storage/utk/dc_dgl/src/runtime/c_runtime_api.cc:88: Check failed: allow_missing: Device API gpu is not enabled. Please install the cuda version of dgl.
Stack trace:
  [bt] (0) /storage/utk/miniconda3/envs/ducati/lib/python3.10/site-packages/dgl-0.9-py3.10-linux-x86_64.egg/dgl/libdgl.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x80) [0x7fbea0dbcc90]
  [bt] (1) /storage/utk/miniconda3/envs/ducati/lib/python3.10/site-packages/dgl-0.9-py3.10-linux-x86_64.egg/dgl/libdgl.so(dgl::runtime::DeviceAPIManager::GetAPI(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)+0x2ab) [0x7fbea10f46cb]
  [bt] (2) /storage/utk/miniconda3/envs/ducati/lib/python3.10/site-packages/dgl-0.9-py3.10-linux-x86_64.egg/dgl/libdgl.so(dgl::runtime::DeviceAPI::Get(DLDeviceType, bool)+0x226) [0x7fbea10efaa6]
  [bt] (3) /storage/utk/miniconda3/envs/ducati/lib/python3.10/site-packages/dgl-0.9-py3.10-linux-x86_64.egg/dgl/libdgl.so(dgl::runtime::NDArray::PinData(DLTensor*)+0x134) [0x7fbea110c484]
  [bt] (4) /storage/utk/miniconda3/envs/ducati/lib/python3.10/site-packages/dgl-0.9-py3.10-linux-x86_64.egg/dgl/libdgl.so(dgl::UnitGraph::PinMemory_()+0x112) [0x7fbea1262672]
  [bt] (5) /storage/utk/miniconda3/envs/ducati/lib/python3.10/site-packages/dgl-0.9-py3.10-linux-x86_64.egg/dgl/libdgl.so(dgl::HeteroGraph::PinMemory_()+0x2e) [0x7fbea1154d0e]
  [bt] (6) /storage/utk/miniconda3/envs/ducati/lib/python3.10/site-packages/dgl-0.9-py3.10-linux-x86_64.egg/dgl/libdgl.so(+0x5af975) [0x7fbea1166975]
  [bt] (7) /storage/utk/miniconda3/envs/ducati/lib/python3.10/site-packages/dgl-0.9-py3.10-linux-x86_64.egg/dgl/libdgl.so(DGLFuncCall+0x60) [0x7fbea10f39f0]
  [bt] (8) /storage/utk/miniconda3/envs/ducati/lib/python3.10/lib-dynload/../../libffi.so.8(+0xa052) [0x7fc0b83dd052]
```

I would appreciate if someone can help what am I missing here?
I have seen various DGL articles and have followed the same steps for CUDA build, but it still throws the same error.

**Comment by initzhang** [comment]
Hi, according to the error message, I guess you didn't open the USE_CUDA option during cmake?
I have updated the readme with more details, please try and tell me if it works :)

**Comment by UtkrishtP** [comment]
@initzhang 
Thanks a lot for your quick reply.

I did use DUSE_CUDA=ON, but I see now that you have updated the readme, let me follow the steps.

Also, is there any requirement for python version too? I’m working with the latest one.

**Comment by UtkrishtP** [comment]
Seems we need python <= 3.9.
With latest versions it's not able to locate torch == 1.9 version

**Comment by UtkrishtP** [comment]
```


(ducati) utkrisht@chisel-3:/storage/utk/DUCATI_SIGMOD$ pip list | grep torch
torch              1.9.1+cu102
torchmetrics       0.8.2
(ducati) utkrisht@chisel-3:/storage/utk/DUCATI_SIGMOD$ pip list | grep dgl
dgl                0.9
(ducati) utkrisht@chisel-3:/storage/utk/DUCATI_SIGMOD$
```

With the above installations and following the readme, Im still getting the same error.

```
raise DGLError(py_str(_LIB.DGLGetLastError()))
dgl._ffi.base.DGLError: [20:53:40] /storage/utk/dc_dgl/src/runtime/c_runtime_api.cc:88: Check failed: allow_missing: Device API gpu is not enabled. Please install the cuda version of dgl.
```

**Comment by UtkrishtP** [comment]
I see that in the paper it's mentioned DUCATI has been built on top of DGL 0.8, but here I see DGL installed version is 0.9 even after cloning this repo, is this okay?

**Comment by initzhang** [comment]
Hi, the 0.9 version number is correct since our code is a modification of DGL 0.8 codebase.
I think the problem is about the build of dgl's cuda support. I have updated the readme again, could you give it a try?

what's more, during your build, did you see some error messages about CUDA?

**Comment by UtkrishtP** [comment]
[build.log](https://github.com/initzhang/dc_dgl/files/12305428/build.log)

Build seems clean, but apparently nothing related to CUDA has been printed, very strange..

**Comment by UtkrishtP** [comment]
Seems error during build, but I dont know why the build is still happening successfully:

```
/storage/utk/dc_dgl/third_party/tensorpipe/tensorpipe/common/fd.cc: In member function ‘tensorpipe::Error tensorpipe::Fd::readFull(void*, size_t)’:
/storage/utk/dc_dgl/third_party/tensorpipe/tensorpipe/common/fd.cc: In member function ‘tensorpipe::Error tensorpipe::Fd::writeFull(const void*, size_t)’:
```

**Comment by initzhang** [comment]
> [build.log](https://github.com/initzhang/dc_dgl/files/12305428/build.log)
> 
> Build seems clean

I didn’t see any gpu kernels got compiled in your build log.  So I guess that the problem is in the cuda path configuration in your CMAKE phase instead. Could you provide your cmake output?

**Comment by UtkrishtP** [comment]
[cmake.log](https://github.com/initzhang/dc_dgl/files/12305683/cmake.log)

**Comment by initzhang** [comment]
Hi, below shows my cmake log, the key difference I find here is that mine didn't rely on the `FindCUDA.cmake` module, also the cuda version is not the same as yours. 
> (test_dc) lccpu22 /home/data/xzhanggb/work/tmp/dc_dgl/build ⇨  cmake -DBUILD_TORCH=ON -DUSE_CUDA=ON -DCMAKE_C_COMPILER=/usr/local/bin/gcc7 -DCMAKE_CXX_COMPILER=/usr/local/bin/g++7 ..
> -- Start configuring project dgl
> -- Build with CUDA support
> -- Found CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-10.2
> -- Found CUDA_CUDART_LIBRARY=/usr/local/cuda-10.2/lib64/libcudart.so
> -- Found CUDA_CUBLAS_LIBRARY=/usr/local/cuda-10.2/lib64/libcublas.so
> -- Found CUDA_CURAND_LIBRARY=/usr/local/cuda-10.2/lib64/libcurand.so
> -- Detected CUDA of version 10.2. Use external CUB/Thrust library.
> -- Found OpenMP_C: -fopenmp (found version "4.5") 
> -- Found OpenMP_CXX: -fopenmp (found version "4.5") 
> -- Build with OpenMP.
> -- Build with LIBXSMM optimization.
> -- -fopenmp -O2 -Wall -fPIC -std=c++14  -DUSE_AVX -DUSE_LIBXSMM -DDGL_CPU_LLC_SIZE=40000000 -DIDXTYPEWIDTH=64 -DREALTYPEWIDTH=32
> -- Running GPU architecture autodetection
> -- Found CUDA arch 7.5 7.5 7.5 7.5 7.5 7.5 7.5 7.5
> -- CUDA flags: -Xcompiler ,-fopenmp,-O2,-Wall,-fPIC,-std=c++14,,-DUSE_AVX,-DUSE_LIBXSMM,-DDGL_CPU_LLC_SIZE=40000000,-DIDXTYPEWIDTH=64,-DREALTYPEWIDTH=32;--expt-relaxed-constexpr;-gencode;arch=compute_75,code=sm_75;--expt-extended-lambda;-Wno-depr> ecated-declarations;-std=c++14
> -- Found OpenMP_C: -fopenmp (found version "4.5") 
> -- Found OpenMP_CXX: -fopenmp (found version "4.5") 
> -- /home/data/xzhanggb/work/tmp/dc_dgl/third_party/dmlc-core/cmake/build_config.h.in -> include/dmlc/build_config.h
> -- summary of build options:
>     Install prefix:  /usr/local
>     Target system:   Linux
>     Compiler:
>       C compiler:    /usr/local/bin/gcc7
>       CFLAGS:         -fopenmp -O2 -Wall -fPIC  -DUSE_AVX -DUSE_LIBXSMM -DDGL_CPU_LLC_SIZE=40000000 -DIDXTYPEWIDTH=64 -DREALTYPEWIDTH=32 -DLINUX -D_FILE_OFFSET_BITS=64 -std=c99 -fno-strict-aliasing -march=native -fPIC -Werror -Wall  > -Wno-unused-function -Wno-unused-but-set-variable -Wno-unused-variable -Wno-unknown-pragmas -DNDEBUG -DNDEBUG2 -DHAVE_EXECINFO_H -DHAVE_GETLINE -O3
> 
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/data/xzhanggb/work/tmp/dc_dgl/build

I think maybe you can try two things:
(1)  manually specify the cuda path in cmake, and if possible use cu102 path (since you installed the cu102 PyTorch, maybe this can avoid some version incompatible problems)
(2) start with the original DGL v0.8 codebase where I didn't modify anything yet (checkout commit ID `b2ec5a2` of this repo) and build from source with cuda. Then test if the DGL cuda is properly installed. This can verify whether the problem resides in my modification or in DGL v0.8 codebase instead.

**Comment by UtkrishtP** [comment]
I followed the above steps.

- Installed cuda 10.2 along with gcc/g++ 8
- Built DGL v0.8 from source, below are the logs and we can see the GPU kernels are being compiled.
[build_.log](https://github.com/initzhang/dc_dgl/files/12312975/build_.log)
[cmake_.log](https://github.com/initzhang/dc_dgl/files/12312976/cmake_.log)

```
$ pip list | grep dgl
dgl                0.8.2.post1
```
- I used the same gcc/g++-8 for dc_dgl but still the GPU kernels are not being compiled., seems to be some issue with this repo.

- Also everytime when i build this repo the following error is thrown even if I specify my path explicitly, I have to delete the CMakeCache file everytime.(Something is hardcoded it seems)
[cmake.log](https://github.com/initzhang/dc_dgl/files/12313041/cmake.log)
[build.log](https://github.com/initzhang/dc_dgl/files/12313109/build.log)

```
CMake Error at CMakeLists.txt:2 (project):                                                                                                                               
  The CMAKE_C_COMPILER:                                                                                                                                                  
                                                                                                                                                                         
    /usr/local/bin/gcc7                                                                                                                                                  
                                                                                                                                                                         
  is not a full path to an existing compiler tool.                                                                                                                       
                                                                                                                                                                         
  Tell CMake where to find the compiler by setting either the environment                                                                                                
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to                                                                                            
  the compiler, or to the compiler name if it is in the PATH.                                                                                                            
                                                                                                                                                                         
                                                                                                                                                                         
CMake Error at CMakeLists.txt:2 (project):                                                                                                                               
  The CMAKE_CXX_COMPILER:                                                                                                                                                

    /usr/local/bin/g++7

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.
```

cmake command used:

```
cmake -DBUILD_TORCH=ON -DUSE_CUDA=ON -DCMAKE_C_COMPILER=/usr/bin/gcc-8 -DCMAKE_CXX_COMPILER=/usr/bin/g++-8 ..
```

**Comment by UtkrishtP** [comment]
Seems like this part is missing in dc_dgl repo's build, which is preventing initiate GPU build:

```
100%] Linking CXX shared library libtensoradapter_pytorch_1.9.1.so
[100%] Built target tensoradapter_pytorch_1.9.1
'libtensoradapter_pytorch_1.9.1.so' -> '/storage/utk/test/dgl/build/tensoradapter/pytorch/libtensoradapter_pytorch_1.9.1.so'
[ 50%] Built target tensoradapter_pytorch
```

**Comment by initzhang** [comment]
Hi, indeed there is a hard-coded path in the build file, thanks for your remind!
I have fixed it now, could you try again?

**Comment by UtkrishtP** [comment]
I should have shared the above error in the first comment, I have been ignoring it since then. 
Works like a charm now.

```
==================
test installation
test successful
==================
```

Thanks a lot for your proactive response :)

**Comment by UtkrishtP** [comment]
I should have shared the above error in the first comment, I have been ignoring it since then. 
Works like a charm now.

```
==================
test installation
test successful
==================
```

Thanks a lot for your proactive response :)
